# This workflow is the primary CI workflow for the project.
# It is triggered on every push to the main branch and on every pull request to the main branch.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
      
    # Install dependencies
    - name: Install dependencies
      run: |
        go mod tidy
        go get .

    # Build
    - name: GoReleaser build Action
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        # Arguments to pass to GoReleaser
        args: build --clean --single-target --snapshot

    # Run unit tests
    - name: Test
      run: go mod tidy; go test -v ./...
